Update publish.yml : update to last state

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -30,7 +30,7 @@ jobs:
           echo "[pub] string is missing in commit message, skipping ..."
           exit 0
 
-      - name: Clone another repo into folder xxx
+      - name: Get Fulltext search index builder
         env:
           TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
@@ -83,6 +83,15 @@ jobs:
             echo "::endgroup::"
           done
           echo "exists=true" >> $GITHUB_OUTPUT
+          
+          dir=_base
+          if [ -d "$dir" ]; then
+            cd $dir
+            touch _config.txt
+            zip -r -9 ../_output/Help-.zip .
+            cd ..
+          fi
+          
           echo "Bundling finished."
 
       - name: Create tag
@@ -100,23 +109,29 @@ jobs:
           
           TAG="$VERSION"
 
-          echo "::group::Old release delete"
-          RELEASE_ID=$(curl -s -H "Authorization: token $TOKEN" \
-            https://api.github.com/repos/$REPO/releases/tags/$TAG | jq -r .id)
-
-          if [ "$RELEASE_ID" != "null" ]; then
-            echo "Deleting release ID $RELEASE_ID"
-            curl -s -X DELETE -H "Authorization: token $TOKEN" \
-              https://api.github.com/repos/$REPO/releases/$RELEASE_ID
-          fi
-          echo "::endgroup::"
-          
-          echo "::group::Old tag delete"
-          if git ls-remote --tags origin | grep -q "$TAG"; then
-            git tag -d "$TAG" || true
-            git push origin ":refs/tags/$TAG" || true
-          fi
-          echo "::endgroup::"
+          #echo "::group::Old release delete"
+          #RELEASE_ID=$(curl -s -H "Authorization: token $TOKEN" \
+          #  https://api.github.com/repos/$REPO/releases/tags/$TAG)
+          #MESSAGE=$(echo "$RELEASE_ID" | jq -r '.message // empty')
+          #if [ "$MESSAGE" = "Not Found" ]; then
+          #  echo "Release with tag $TAG not found"
+          #else
+          #  RELEASE_ID =$(echo "RELEASE_ID" | jq -r '.id // empty')
+          #  
+          #  if [ "$RELEASE_ID" != "null" ]; then
+          #    echo "Deleting release ID $RELEASE_ID"
+          #    curl -s -X DELETE -H "Authorization: token $TOKEN" \
+          #      https://api.github.com/repos/$REPO/releases/$RELEASE_ID
+          #  fi
+          #fi
+          #echo "::endgroup::"
+          #
+          #echo "::group::Old tag delete"
+          #if git ls-remote --tags origin | grep -q "$TAG"; then
+          #  git tag -d "$TAG" || true
+          #  git push origin ":refs/tags/$TAG" || true
+          #fi
+          #echo "::endgroup::"
 
           echo "::group::New tag created"
           echo "tag=$TAG" >> $GITHUB_OUTPUT
